"$schema" = 'https://starship.rs/config-schema.json'

format = """\
[](bg:#030B16 fg:#7DF9AA)\
$os\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
[](fg:#7DF9AA bg:#3B76F0)\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
[](fg:#3B76F0 bg:#FCF392)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
[](fg:#FCF392 bg:#030B16)\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$container\
$shell\
$character
"""

[os]
disabled = false
style = "bg:#7DF9AA fg:#090c0c"

[os.symbols]
# TODO: add more NF icons as needed https://starship.rs/config/#os
Fedora = " "
Linux = " "
Macos = "󰀵 "

[directory]
format = "[   $path ]($style)"
style = "fg:#E4E4E4 bg:#3B76F0"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
style = "fg:#1C3A5E bg:#FCF392"

[git_status]
format = '[$all_status]($style)'
style = "fg:#1C3A5E bg:#FCF392"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#1C3A5E bg:#FCF392"
deleted_style = "fg:bright-red bg:235"
disabled = false

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:bright-white bg:18"

[character]
success_symbol = '[ ➜](bold green) '
error_symbol = '[ ✗](#E84D44) '

[time]
disabled = false
time_format = "%R"             # Hour:Minute Format
style = "fg:#8DFBD2"           # bg:#1C3A5E
format = '[ 󱑍 $time ]($style)'

[dotnet]
format = "[ $symbol($version )\\($tfm\\) ]($style)"
symbol = " .NET"
version_format = "${major}"

[nodejs]
format = "[ $symbol($version )]($style)"

[python]
format = "[ ${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"
symbol = " "

[package]
format = " [$symbol$version]($style) "

[nix_shell]
format = " [$symbol$state( \\($name\\))]($style) "
