"$schema" = 'https://starship.rs/config-schema.json'

# generally speaking:
# Nerdfont icons: yes
# icons better than words
# clean prompt area

# the basic idea of the format here
# is to keep less regularly used features discoverable
# so we turn everything on,
# but only really configure stuff we know about.
# when new contextual stuff is discovered, it can be configured then.

# we use left and right prompts
# line 1: unconfigured stuff
# line 2: path                    env?
# line 3: time, prompt            duration

add_newline = true

format = """
$singularity\
$kubernetes\
$shlvl\
$nats\
$pijul_channel\
$pulumi\
$conda\
$bun\
$buf\
$c\
$cmake\
$crystal\
$daml\
$dart\
$deno\
$direnv\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$go\
$gradle\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$lua\
$meson\
$nim\
$nodejs\
$ocaml\
$odin\
$opa\
$openstack\
$package\
$perl\
$php\
$purescript\
$python\
$quarto\
$rlang\
$raku\
$ruby\
$red\
$rust\
$scala\
$solidity\
$spack\
$swift\
$typst\
$vagrant\
$vlang\
$zig\

$terraform\
$docker_context\
$nix_shell\
$container\

$line_break\
[](bg:#030B16 fg:#3B76F0)\
$directory\
[](fg:#3B76F0 bg:#FCF392)\

$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fossil_branch\
$fossil_metrics\
$hg_branch\
$vcsh\
[](fg:#FCF392 bg:#030B16)\

$line_break\
$battery\
$time\
$status\
$os\
$character\
"""

right_format = """
$username\
$hostname\
$localip\

$cmd_duration\
$jobs\
"""

[os]
disabled = false
format = " [$symbol]($style) "
# style = "bg:#7DF9AA fg:#090c0c"


[os.symbols]
# TODO: add more NF icons as needed https://starship.rs/config/#os
Fedora = "  "
Linux = "  "
Macos = " 󰀵 "

[directory]
format = "[   $path ]($style)"
style = "fg:#E4E4E4 bg:#3B76F0"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
style = "fg:#1C3A5E bg:#FCF392"

[git_status]
format = '[$all_status]($style)'
style = "fg:#1C3A5E bg:#FCF392"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#1C3A5E bg:#FCF392"
deleted_style = "fg:bright-red bg:235"
disabled = false

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:bright-white bg:18"

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](#E84D44)'

[time]
disabled = false
time_format = "%R"           # Hour:Minute Format
style = "fg:#8DFBD2"         # bg:#1C3A5E
format = '[󱑍 $time]($style)'

[dotnet]
format = "[ $symbol($version )\\($tfm\\) ]($style)"
symbol = " .NET"
version_format = "${major}"

[nodejs]
format = "[ $symbol($version )]($style)"

[python]
format = "[ ${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"
symbol = " "

[package]
format = " [$symbol$version]($style) "

[nix_shell]
format = " [$symbol$state( \\($name\\))]($style) "
